### ISSUE TITLE
Question on Julia bounds

### ISSUE THREAD

**Issue by itsdfish** [tpapp/StanDump.jl#7]
Hi Tamas, 

I have encountered a version conflict at [MCMCChains](https://github.com/TuringLang/MCMCChains.jl/pull/271) , which appears to be due to the bounds you have on the version of Julia. I was wondering if this is a hard requirement?

Thanks

**Comment by tpapp** [comment]
I don't quite recall, but it must be some language feature. If you really, really need 1.0, PRs are welcome, but I can't promise support for 1.0 once the new LTS will be out.

**Comment by itsdfish** [comment]
I'm closing this issue because we found a workaround.
